apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: server-hpa
  namespace: superapp
spec:
  maxReplicas: 25
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-deployment
  targetCPUUtilizationPercentage: 60