apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pgpasswordspc
  namespace: superapp
spec:
  parameters:
    clientID: 13766221-dd74-4403-b37c-d67a30653f23
    keyvaultName: kv-appsuperappviipocxpkf
    objects: |
      array:
        - |
          objectName: pgpassword
          objectType: secret
    tenantId: 449fbe1d-9c99-4509-9014-4fd5cf25b014
  provider: azure
  secretObjects:
  - data:
    - key: pgpassword
      objectName: pgpassword
    secretName: pgpassword
    type: Opaque